### ISSUE TITLE
`kvrocks.apache.org` or `kvrocks.rockslabs.com`

### ISSUE THREAD

**Issue by jiayouxujin** [RocksLabs/kvrocks-operator#12]
Hi, members of rockslabs.
I try to modify the definition of name in crd. And since the kvrocks-operator is still under the rockslabs organization, is it appropriate to use `kvrocks.apache.org`?

**Comment by jiayouxujin** [comment]
cc @git-hulk  @shangxiaoxiong

**Comment by git-hulk** [comment]
Yes, I think it's fine to use kvrocks.apache.org, since we will move this repo into the apache organization soon.

**Comment by jiayouxujin** [comment]
OK, I will rename it!
