### ISSUE TITLE
Test and then Remove the description in the README about rebuilding the image.

### ISSUE THREAD

**Issue by ColinChamber** [RocksLabs/kvrocks-operator#15]
As https://github.com/apache/incubator-kvrocks/pull/1415 has been merged, users no longer need to rebuild the image to use kvrocks-operator.

- [x] Try creating a cluster using the apache/kvrocks:nightly image. 
- [x] If everything is OK, update the README.

**Comment by xiao-jay** [comment]
I can try to solve this issue
