### ISSUE TITLE
In the standard type, the storage size of PVCs for Sentinel and KVrocks instances can only be the same.

### ISSUE THREAD

**Issue by ColinChamber** [RocksLabs/kvrocks-operator#37]
The logic for creating PVCs between these two should be distinguished. Kvrocks instances may require larger storage size, but Sentinel does not.

**Comment by tianshimoyi** [comment]
Sentinel clusters do not require persistent storage

**Comment by jiayouxujin** [comment]
Thanks @tianshimoyi @ColinChamber 
Now I've separated the code for kvrocks and sentinel. I'm using deployment to create sentinel, and using emptydir as the data volume.
https://github.com/RocksLabs/kvrocks-operator/pull/36/files#diff-46f6482b49eadbf34413755b425c88e4032c00027901225a4feacde6e78b9d44R62

**Comment by ColinChamber** [comment]
> Sentinel clusters do not require persistent storage

Before #36, when creating sentinels, it would call the [NewStatefulSet](https://github.com/RocksLabs/kvrocks-operator/blob/e04d9a7d72b15568cc171f3f961aba40804d61ad/pkg/resources/statefulset.go#L142) function, which would require persistent storage.
