### ISSUE TITLE
The request and limit parameters in Sentinel Instance cannot be modified in the configuration.

### ISSUE THREAD

**Issue by ColinChamber** [RocksLabs/kvrocks-operator#38]
Avoid making key configurations hardcoded. [Here](https://github.com/RocksLabs/kvrocks-operator/blob/1428825637499f101b04e5631166a6098dee3d9c/pkg/resources/kvrocks.go#L92).

**Comment by tianshimoyi** [comment]
The operator does not want you to create a sentinel cluster yourself, it will automatically identify the sentinel cluster you need and create it. If you need customized processing, CRD supports sentinel type CR identification

![截屏2023-06-19 下午5 42 19](https://github.com/RocksLabs/kvrocks-operator/assets/68532999/22d4af8f-6466-4382-b191-c68510215e9e)

**Comment by jiayouxujin** [comment]
Hi, @tianshimoyi @ColinChamber 
Under the condition of not wanting users to create their own sentinel clusters, do you think we need to provide a field for users to specify the replicas and resource requirements of sentinel? For instance, changing `EnableSentinel` to `SentinelConfig`.

```go
type SentinelConfig struct{
   EnableSentinel bool
   Replicas int32
   Resources *corev1.ResourceRequirements
}
```

I have based the current default resource settings on the redis-operator.
https://github.com/RocksLabs/kvrocks-operator/pull/36/files#diff-a8a584490794acc39bdbcd0073aabf63d756cf54f53900751cecaf596af1a070R90

https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L505

**Comment by tianshimoyi** [comment]
@jiayouxujin You can create a sentinel cluster first, and specify information such as resources, so that you can customize sentinel

**Comment by jiayouxujin** [comment]
@tianshimoyi OK, I get it.
If there is no sentinel in the current k8s cluster and `enableSentinel` is true, operator will automatically create a default sentinel.
