### ISSUE TITLE
Service does not distinguish master and slave nodes

### ISSUE THREAD

**Issue by ColinChamber** [RocksLabs/kvrocks-operator#40]
![image](https://github.com/RocksLabs/kvrocks-operator/assets/95634254/c6dceb78-9d20-40f4-af61-b9dfcf058847)

**Comment by ColinChamber** [comment]
Do you think we should create two services? One of them would point to the master node, and the other would point to the slave nodes. @jiayouxujin @git-hulk @tianshimoyi

**Comment by tianshimoyi** [comment]
@ColinChamber The connection uses the service ip of sentinel, so it is not necessary to create ip for both master and slaver

**Comment by ColinChamber** [comment]
Got it. Thanks @tianshimoyi
