### ISSUE TITLE
Add CI to check and linter the Go code style

### ISSUE THREAD

**Issue by git-hulk** [RocksLabs/kvrocks-operator#7]
For more detail can see: https://github.com/KvrocksLabs/kvrocks_controller/blob/unstable/.github/workflows/ci.yaml

**Comment by ColinChamber** [comment]
OK, I will add it.

**Comment by xiao-jay** [comment]
@git-hulk hello, Can i try this issue?

**Comment by xiao-jay** [comment]
@git-hulk  This project have roadmap or something? I don't know how to contribute.

**Comment by git-hulk** [comment]
> @git-hulk hello, Can i try this issue?

Not sure if @ColinChamber has already on it.

> @git-hulk This project have roadmap or something? I don't know how to contribute.

To see if @ColinChamber @jiayouxujin can create a roadmap for this project.

**Comment by xiao-jay** [comment]
> OK, I will add it.

@ColinChamber I see you have assigned yourself, but you haven't mentioned PR yet. Can I participate in this issue？

**Comment by ColinChamber** [comment]
@xiao-jay Of course, everyone is welcome to participate

**Comment by jiayouxujin** [comment]
@xiao-jay Welcome to participate.  I'm making e2e test work (because we're going to refactor some code, and I think making the test feasible first is a good solution). 
After testing it locally, I will split some issues. You are welcome to participate.

**Comment by xiao-jay** [comment]
> @xiao-jay Welcome to participate. I'm making e2e test work (because we're going to refactor some code, and I think making the test feasible first is a good solution). After testing it locally, I will split some issues. You are welcome to participate.

ok,look forward to it.
